version: '3'

services:
  db:
    image: postgres:14.7
    env_file:
      - .env.production.db
    volumes:
       - database:/var/lib/postgresql/data
       - ./backend/database/init_all_docker.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "54320:5432"
    restart: always

  api:
    build: ./backend
    environment:
      PGPASSFILE: /app/pass.pgpass
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always

volumes:
  database:
