version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: elvfdpqrnxskmaiydwl
    volumes:
       - database:/var/lib/postgresql/data
       - ./backend/database/init_all_docker.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "54320:5432"
    restart: always

  api:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always

volumes:
  database:
