version: '3'

services:
  db:
    image: postgres:14.7
    env_file:
      - .env.production.db
    volumes:
       - database:/var/lib/postgresql/data
       - ./backend/database/init_all_docker.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "54320:5432"
    restart: always
    networks:
      - server-side

  api:
    build: ./backend
    environment:
      PGPASSFILE: /app/pass.pgpass
    ports:
      - "8000:8000"
    volumes:
       - ./backend/uploads:/app/uploads
    depends_on:
      - db
    networks:
      - client-side
      - server-side
    restart: always

  frontend:
    build: ./frontend
    ports:
      - 1420:80
    depends_on:
      - api
    networks:
      - client-side

volumes:
  database:

networks:
  client-side:
  server-side:
