apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: api
    spec:
      containers:
        - env:
            - name: PGPASSFILE
              value: /app/pass.pgpass
          image: ghcr.io/eudelins/subscription-manager-api:1.0.0
          name: api
          ports:
            - containerPort: 8000
          resources: {}
          volumeMounts:
            - mountPath: /app/uploads
              name: api-claim0
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      volumes:
        - name: api-claim0
          persistentVolumeClaim:
            claimName: api-claim0
status: {}
