kind: PersistentVolume
apiVersion: v1
metadata:
  name: api-claim0
  labels:
    type: local
    io.kompose.service: api-claim0
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: api-claim0
  labels:
    io.kompose.service: api-claim0
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
