apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  type: NodePort
  ports:
    - name: "frontend-port"
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30011
  selector:
    io.kompose.service: frontend
status:
  loadBalancer: {}
