name: Rust CI

on:
  pull_request:
    branches:
      - main
  push:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure cargo / rust env
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build and test
        run: |
          cargo build --all --verbose
          cargo test --all --verbose
